Tonette/UI add staff page
chevyB/pcbee pull request #16
Opened 2023-12-21 18:05 UTC by Kiel-1401

## Notice for Reviewers

## Summary / 概要

### JIRA

https://app.asana.com/0/1206058275306783/<00000000000000>/f

## Screenshots/Videos

### New scenarios / Expected Behaviors

- [ ] There are no new scenarios
- [ ] There are new scenarios
  - [ ] ...
  - [ ] ...

### URL for reviewers

![406851600_341622762155546_7433386070189833565_n](https://github.com/chevyB/pcbee/assets/89174822/48f79441-428d-4409-b6e6-81361cb0844b)

2023-12-22 02:08 UTC, chevyB commented on web/src/pages/createStaff/index.page.jsx
> +      <form className="mt-10 ml-4 w-1/2 lg:w-1/4  ">
1. About margin and padding. So much unneccessary classnames, where you can merge it in the div if we have it. 
2. Dont limit the width for now. 
3. The spaces between Inputs can be declared on the wrapper/parent/form component so you dont need to add `mt-5` every single time. Pls utilize it.
```suggestion

      <form className="flex flex-col gap-4">
```

2023-12-22 02:08 UTC, chevyB commented on web/src/pages/createStaff/index.page.jsx
> +         <div className>
Unnecessary code: div that dont have className. . Remove it
```suggestion
```

2023-12-22 02:08 UTC, chevyB commented on web/src/pages/createStaff/index.page.jsx
> +                                                </div>
1. IMPORTANT: Please observer proper indention please
2. div mt-5 is not needed, it should be handled in the the wrapper/parent/form component
```suggestion
         <TextInput label='Name' name='createStaff' />
         <TextInput label='Position' name='createStaff' />
         <TextInput label='Contact Number' name='createStaff' />
         <TextInput label='Account Type' name='createStaff' />
```

2023-12-22 02:08 UTC, chevyB commented on web/src/pages/createStaff/index.page.jsx
> +            </Button>
1. too much styling
2. Pls utilize tailwind instead of this vanilla CSS
```suggestion
            <Button color='warning' type='submit' >
              Submit
            </Button>
```

2023-12-22 02:08 UTC, chevyB commented on web/src/pages/createStaff/index.page.jsx
> +import { Button } from 'flowbite-react';
IMPORTANT:
1. I already gave a feedback to you about proper routing
2. This file should be 
 `web/src/pages/staffs/new/index.page.jsx`

So you can access this page using
`http://localhost:3000/staffs/new`

2023-12-22 02:08 UTC, chevyB commented on web/src/components/atoms/Toasts.jsx
> +import { Toast } from 'flowbite-react';
Why there is a change on this file?

2023-12-22 02:08 UTC, chevyB commented on web/src/components/organisms/createstaffs.jsx
> +import { Button } from 'flowbite-react'
This file is not in use right? Delete this

2023-12-26 04:08 UTC, chevyB commented
can i ask for updates?

2023-12-28 15:46 UTC, Kiel-1401 commented on web/src/pages/createStaff/index.page.jsx
> +      <form className="mt-10 ml-4 w-1/2 lg:w-1/4  ">
sir chev goodevening po .. regarding anii po na codeblock gi follow nakoo ang suggested change po. supposedly ingani po ba ang mahitabo sa mga feild? 
![image](https://github.com/chevyB/pcbee/assets/89174822/24a16da9-11f7-4cfd-9a46-ce2c705aa670)

2023-12-28 15:51 UTC, Kiel-1401 commented on web/src/pages/createStaff/index.page.jsx
> +      <form className="mt-10 ml-4 w-1/2 lg:w-1/4  ">
![image](https://github.com/chevyB/pcbee/assets/89174822/58c4474f-5675-41c9-b9b6-b97debdf5e53)

2024-01-04 01:43 UTC, chevyB requested changes

2024-01-04 01:43 UTC, chevyB commented on web/src/pages/staffs/new/index.page.jsx
> +          style={{ width: 140, height: 55 }}
remove height
```suggestion
          style={{ width: 140 }}
```

2024-01-05 13:27 UTC, Kiel-1401 commented on web/src/pages/staffs/new/index.page.jsx
> +          style={{ width: 140, height: 55 }}
Sir good evening na remove na po nako ang height po sa button bali ingani na sya 
![image](https://github.com/chevyB/pcbee/assets/89174822/f3909b97-359c-4a13-b6d5-22d196e66f53)

2024-01-05 13:44 UTC, chevyB approved these changes

2024-01-05 13:44 UTC, merged