Create api endpoint
chevyB/pcbee pull request #17
Opened 2023-12-22 03:53 UTC by Ahykaa

## Notice for Reviewers

## Summary / 概要

### JIRA

https://app.asana.com/0/1206058275306783/1206078052186477/f

## Screenshots/Videos
![Uploading image.png…]()

### New scenarios / Expected Behaviors

- [ ] There are no new scenarios
- [ ] There are new scenarios
  - [ ] ...
  - [ ] ...

### URL for reviewers

2023-12-22 04:06 UTC, chevyB requested changes

2023-12-22 04:06 UTC, chevyB commented on api/routes/api.php
> +    });
1. Should create new controller and transfer the logic there
2. Always add validations
```suggestion
    Route::post('/orders/new', [OrderController::class, 'create']);
```

2023-12-22 04:53 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +class OrderController extends Controller
Nice you covered all resource

2023-12-22 04:53 UTC, chevyB commented on api/routes/api.php
> +    });
No need to add
```suggestion
   // Route::prefix('admin')->group(['middleware' => ['restrictRole:admin']], function () {
   //     // Routes here
    //});
```

2023-12-22 04:53 UTC, chevyB commented on api/routes/api.php
> +    Route::group(['middleware' => ['restrictRole:staff']], function () {
Add here instead
```suggestion
    Route::group(['middleware' => ['restrictRole:staff', 'restrictRole:admin']], function () {
```

2023-12-22 04:58 UTC, Ahykaa commented on api/app/Http/Controllers/OrderController.php
> +class OrderController extends Controller
Sir regarding the read api endpoint, i In-review na nko ?

2023-12-22 05:12 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +class OrderController extends Controller
@Ahykaa yes, get all related task. and transfer the assignment to you

2023-12-22 05:13 UTC, chevyB commented on api/routes/api.php
> +use App\Models\Order;
remove, not used
```suggestion
```

2023-12-22 05:15 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +        $order = Order::findOrFail($id);
Add validation again.
i think better to use this instead to avoid declaring the validation again and again:
https://laravel.com/docs/10.x/validation#creating-form-requests

2023-12-22 05:47 UTC, chevyB commented on api/routes/api.php
> +    });
You deleted the OrderRoute

2023-12-22 05:51 UTC, Ahykaa commented on api/app/Http/Controllers/OrderController.php
> +class OrderController extends Controller
Noted sir

2023-12-22 06:59 UTC, chevyB commented on api/app/Http/Requests/StoreOrderRequest.php
> +        return false;
have you tested in postman and it throws validation error?
because i think this needs to true

2023-12-22 07:01 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +    public function update(Request $request, string $id)
```suggestion
    public function update(StoreOrderRequest $request string $id)
```

2023-12-27 06:03 UTC, Ahykaa commented
Good afternoon sir, I have uploaded the screenshot. I've already received the token, however the orders have an error 404.

2023-12-27 06:07 UTC, chevyB reviewed
To test,

it should be: `http...:<port>/api/orders`

2023-12-27 06:07 UTC, chevyB commented on api/routes/api.php
> +        Route::resource('staff-orders', OrderController::class);
no need to add staff, it doesnt do anything with order or regular apis
```suggestion
        Route::resource('orders', OrderController::class);
```

2023-12-27 07:28 UTC, Ahykaa commented on api/routes/api.php
> +        Route::resource('staff-orders', OrderController::class);
This is the update sir.

![image](https://github.com/chevyB/pcbee/assets/89176216/90fc99a5-29c7-4bc2-bdc5-46227a130e55)
![image](https://github.com/chevyB/pcbee/assets/89176216/0cf2eadf-f276-48f4-ab91-00aa7dd429f7)

2023-12-27 07:35 UTC, chevyB commented on api/routes/api.php
> +        Route::resource('staff-orders', OrderController::class);
The error is same as this:
https://github.com/chevyB/pcbee?tab=readme-ov-file#be-possible-errors

2023-12-27 10:28 UTC, Ahykaa commented on api/routes/api.php
> +        Route::resource('staff-orders', OrderController::class);
Sir, I already try the solution 
![image](https://github.com/chevyB/pcbee/assets/89176216/565dd07c-28fc-4f35-812b-39f55fc2d504)

Same error 
![image](https://github.com/chevyB/pcbee/assets/89176216/3e675f6b-8062-452d-9e10-407598f58493)

2023-12-27 10:47 UTC, chevyB commented on api/routes/api.php
> +        Route::resource('staff-orders', OrderController::class);
This error is has been around for a while already, pls check for solutions here:
https://www.google.com/search?q=laravel+error+storage&oq=laravel+error+storage&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQLhhA0gEINDI0MWowajGoAgCwAgA&sourceid=chrome&ie=UTF-8

2024-01-04 01:45 UTC, chevyB approved these changes

2024-01-04 04:05 UTC, merged