Integratio CORS Error
chevyB/pcbee pull request #20
Opened 2024-01-11 11:43 UTC by Ahykaa

## Notice for Reviewers

## Summary / 概要

### JIRA

https://app.asana.com/0/1206058275306783/<00000000000000>/f

## Screenshots/Videos
Errors in CORS:
![image](https://github.com/chevyB/pcbee/assets/89176216/c895312b-7bd3-4045-882f-48f2e3215240)

### New scenarios / Expected Behaviors

- [ ] There are no new scenarios
- [ ] There are new scenarios
  - [ ] ...
  - [ ] ...

### URL for reviewers

2024-01-15 08:48 UTC, chevyB requested changes

2024-01-15 08:48 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +        return response()->json(['order' => $orders]);
```suggestion
        return response()->json(['orders' => $orders]);
```

2024-01-15 08:48 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +        $validatedData['order_at'] = $order_at;
You add `order_at` in validation but you override it here?
- its conflicting

You can also add default value in migration, so no need to put like this.

2024-01-15 08:48 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +        $validatedData['order_at'] = $order_at;
pls also add user_id
```
$validatedData->user_id = Auth::id();
```

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +    user_id: yup.number().required(),
remove user_id, its not good to include it in API. should be filled in BE.
It will cause system vulnerabilities 
```suggestion
```

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +    store_id: yup.number().oneOf([1, 2, 3]).required(),
I will allow this `.oneOf([1, 2, 3])` but best thing to do is pass the string and check the DB if exists and returns the `id`

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +        .oneOf(['open', 'in-transit', 'delivered', 'cancelled', 'onhold'])
can create a lib file because we will use it not only this page in the future. so we have 1 source of truth
`web/src/hooks/lib/statuses.js`

then inside is

export const statuses  = ['open', 'in-transit', 'delivered', 'cancelled', 'onhold']

then import it

```
import { statuses } from `@/...statuses.jsx`

status: yup
        .string()
        .oneOf(statuses)
```

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +        try {
```suggestion
    const onSubmit = async (data) => {
        try {
```

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +            console.error('API Error:', error)
```suggestion
            router.push(`/orders`)
        } catch (error) {
```

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/index.page.jsx
> +    ]
I will allow this but we have to create an api next time to get the updated list of branches

2024-01-15 08:48 UTC, chevyB commented on web/src/pages/orders/new/index.page.jsx
> +        { value: 8, label: 'Speaker' },
should be handled in BE as well next time. I will allow this for now

2024-01-17 15:40 UTC, chevyB requested changes

2024-01-17 15:40 UTC, chevyB commented on api/database/migrations/2023_12_14_180132_create_orders_table.php
> +            $table->string('part_model')->nullable();
should create new migration file:
`add_part_model_column_to_orders_table`
```
    public function up()
    {
        Schema::table('orders', function (Blueprint $table) {
            $table->string('part_model')->after('brand')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('orders', function (Blueprint $table) {
            $table->dropColumn('part_model');
        });
    }
```

2024-01-19 02:16 UTC, chevyB requested changes
Pls fix unresolved commit and conflict

2024-01-19 02:16 UTC, chevyB commented on api/app/Http/Controllers/OrderController.php
> +        $validatedData['user_id'] = $userId;
No need to create new variable if used once
```suggestion

        $validatedData = $request->validated();
        $category = Category::firstOrCreate(
            ['label' => $validatedData['category_label']],
        );
        $validatedData['category_id'] = $category->id;

        $validatedData['user_id'] = Auth::id();
```

2024-01-19 02:16 UTC, chevyB commented on api/database/seeders/CategorySeeder.php
> +        ], ['id'], ['label', 'created_at', 'updated_at']);
Should be label, make the label unique so it will work.
Also, id is not good to reference because if have data already. Then the label will change it will cause data discrepancy.

```suggestion
        ], ['label'], ['label', 'created_at', 'updated_at']);
```

2024-01-19 02:16 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +        data.order_at = new Date(data.order_at).toISOString().slice(0, 19).replace("T", " ");
instead of manually formatting, can you try like this.
```suggestion
<DatePicker 
  label="Date" 
  name="order_at" 
  dateFormat="yyyy-MM-dd"
  {...formState} 
/>
```

2024-01-19 02:16 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +            console.log('Order created successfully:', order)
```suggestion
```

2024-01-19 10:01 UTC, Ahykaa commented
Good afternoon sir, I've tried using the dateFormat already, but there is an error. I've attached a screenshot of the error. Also, I try installing date-fns, I encounter the same problem message. 
![image](https://github.com/chevyB/pcbee/assets/89176216/080dec94-79ea-4922-9c41-f79af2b2ecc6)

2024-01-19 10:10 UTC, chevyB commented
@Ahykaa may i know the actual value of `order_at`?

You can also follow this to format using yup:
https://www.codedaily.io/tutorials/Yup-Date-Validation-with-Custom-Transform

2024-01-19 13:25 UTC, Ahykaa commented
> @Ahykaa may i know the actual value of `order_at` when not formatted?
> 
> You can also follow this to format using yup: https://www.codedaily.io/tutorials/Yup-Date-Validation-with-Custom-Transform

Is this what you mean sir ?
![image](https://github.com/chevyB/pcbee/assets/89176216/080c0af8-c76b-4608-b566-0bd7d3bd742b)

2024-01-20 03:23 UTC, chevyB approved these changes

2024-01-20 03:23 UTC, chevyB commented on api/database/migrations/2023_12_14_180132_create_orders_table.php
> -            $table->integer('order_number');
why order_number is deleted?

2024-01-20 03:23 UTC, chevyB commented on api/database/migrations/2024_01_19_232916_add_part_model_column_to_orders_table.php
> +<?php
you created 2 add part_model column

2024-01-20 03:23 UTC, chevyB commented on api/database/seeders/CategorySeeder.php
> +        ], ['label'], ['label', 'created_at', 'updated_at']);
```suggestion
        ], ['label'], ['created_at', 'updated_at']);
```

2024-01-20 03:23 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +  order_at: yup.date().default(() => new Date()),
```suggestion
  order_at: yup.date().default(() => new Date()).transform((value) => format(value, "yyyy-MM-dd")),
```

2024-01-20 03:23 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +    data.order_at = format(data.order_at, "yyyy-MM-dd");
```suggestion
```

2024-01-20 03:23 UTC, chevyB requested changes
.

2024-01-22 02:05 UTC, Ahykaa commented on api/database/migrations/2023_12_14_180132_create_orders_table.php
> -            $table->integer('order_number');
I think it's okay to remove, because our order form already has an order ID.

2024-01-22 02:30 UTC, Ahykaa commented on web/src/pages/orders/new/hooks.js
> +    data.order_at = format(data.order_at, "yyyy-MM-dd");
Good morning, sir. I updated the code base on your suggested change. It prompted the same error. 
![image](https://github.com/chevyB/pcbee/assets/89176216/f9139dde-9ee6-4a37-9480-960e1a55055f)

2024-01-22 13:17 UTC, chevyB commented on api/database/migrations/2023_12_14_180132_create_orders_table.php
> -            $table->integer('order_number');
okay

2024-01-22 14:06 UTC, chevyB commented on web/src/pages/orders/new/hooks.js
> +    data.order_at = format(data.order_at, "yyyy-MM-dd");
I think we already have created at sa migration

2024-01-23 01:28 UTC, chevyB approved these changes

2024-01-23 01:28 UTC, merged